// packages/solid/src/index.ts
import core from 'vite-plugin-svg-sprite-components-core';
import { stripIndent } from 'proper-tags';

export default function vitePluginSvgSpriteComponentsReact() {
  return core({
    name: 'svg-sprite-components-solid',
    query: 'sprite-solid',
    serialize({ symbol, symbolHtml, symbolId, inline, filePlaceholder }) {
      const attributes = Object.fromEntries(
        Object.entries(symbol.svg)
          .filter(([key]) => key.startsWith('@_'))
          .map(([key, val]) => [key.replace('@_', ''), val]),
      );
      const attributesCode = Object.entries(attributes)
        .map(([key, val]) => `${key}=${JSON.stringify(val)}`)
        .join(' ');

      if (inline) {
        return stripIndent`
          import { template as _$template } from "solid-js/web";
          import { spread as _$spread } from "solid-js/web";
          const _tmpl$ = /*#__PURE__*/_$template(\`<svg${
            attributesCode ? ` ${attributesCode}` : ''
          }><symbol id="${symbolId}"${
            attributesCode ? ` ${attributesCode}` : ''
          }></symbol><use href="#${symbolId}">\`);
          export default function Comp(props) {
            return (() => {
              const _el$ = _tmpl$(),
                _el$2 = _el$.firstChild;
              _$spread(_el$, props, true, true);
              _el$2.innerHTML = ${JSON.stringify(symbolHtml)
                .replace(/^<svg.+?>/, '')
                .replace(/<\/svg>$/, '')};
              return _el$;
            })();
          }
        `;
      }

      return stripIndent`
        import { template as _$template } from "solid-js/web";
        import { spread as _$spread } from "solid-js/web";
        const _tmpl$ = /*#__PURE__*/_$template(\`<svg${
          attributesCode ? ` ${attributesCode}` : ''
        }><use href="${filePlaceholder}#${symbolId}">\`);
        export default function Comp(props) {
          return (() => {
            const _el$ = _tmpl$();
            _$spread(_el$, props, true, true);
            return _el$;
          })();
        }
      `;
    },
  });
}

// packages/react/src/index.ts
import core from 'vite-plugin-svg-sprite-components-core';
import { stripIndent } from 'proper-tags';

export default function vitePluginSvgSpriteComponentsReact() {
  return core({
    name: 'svg-sprite-components-react',
    query: 'sprite-react',
    serialize({ symbol, symbolHtml, symbolId, inline, filePlaceholder }) {
      const attributes = Object.fromEntries(
        Object.entries(symbol.svg)
          .filter(([key]) => key.startsWith('@_'))
          .map(([key, val]) => [key.replace('@_', ''), val]),
      );
      const attributesCode = Object.entries(attributes)
        .map(([key, val]) => `${key}: ${JSON.stringify(val)}`)
        .join(',\n');

      if (inline) {
        return stripIndent`
          import { forwardRef } from 'react';
          import { jsx as _jsx } from "react/jsx-runtime";
          export default /*#__PURE__*/forwardRef(function Icon(props, ref) {
            return /*#__PURE__*/_jsx("svg", {
              ${attributesCode},
              ...props,
              ref: ref,
              children: [/*#__PURE__*/_jsx("symbol", {
                ${attributesCode},
                id: "${symbolId}",
                dangerouslySetInnerHTML: {
                  __html: ${JSON.stringify(
                    symbolHtml.replace(/^<svg.+?>/, '').replace(/<\/svg>$/, ''),
                  )}
                }
              }), /*#__PURE__*/_jsx("use", {
                href: "#${symbolId}"
              })]
            });
          });
        `;
      }

      return stripIndent`
        import { forwardRef } from 'react';
        import { jsx as _jsx } from "react/jsx-runtime";
        export default forwardRef(function Icon(props, ref) {
          return /*#__PURE__*/_jsx("svg", {
            ${attributesCode},
            ...props,
            ref: ref,
            children: /*#__PURE__*/_jsx("use", {
              href: "${filePlaceholder}#${symbolId}"
            })
          });
        });
      `;
    },
  });
}
